{% set name = "openinference-instrumentation-bedrock" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/openinference_instrumentation_bedrock-{{ version }}.tar.gz
  sha256: e4f06c8428c3a74617a04e660dbaa4cd465bdbe75ceeb3008ddb1e5870bb7574

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<3.12
    - hatchling
    - pip
  run:
    - python >=3.8,<3.12
    - opentelemetry-api
    - opentelemetry-instrumentation >=0.1.5
    - opentelemetry-semantic-conventions
    - openinference-semantic-conventions
    - wrapt
    - botocore

test:
  imports:
    - openinference.instrumentation.bedrock

about:
  summary: OpenInference Bedrock Instrumentation
  home: https://github.com/Arize-ai/openinference
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - michaelschiff
    - mikeldking
    - RogerHYang
    - axiomofjoy
    - anticorrelator
